// EA Activity structured rows: the synthesize API streams newline-delimited
// JSON (one activity per line). Parsing is tolerant of partial trailing
// lines (mid-stream), code fences, and stray commentary.
//
// Rows come from two places: harvested straight out of a note's approved
// "## SFDC Activity Entry" section (origin "note"), or generated by Claude
// from a raw note (origin "generated").

import { normalizePair } from "@/lib/sfdcTaxonomy";

export function parseActivityRows(text) {
  const rows = [];
  for (const rawLine of (text || "").split("\n")) {
    const line = rawLine.trim().replace(/^```(?:json)?/, "").replace(/```$/, "").trim();
    if (!line.startsWith("{")) continue;
    let obj;
    try { obj = JSON.parse(line); } catch { continue; }
    if (!obj || typeof obj !== "object") continue;
    if (!obj.title && !obj.comments) continue;
    // Normalize onto the canonical Salesforce picklist so a legacy or
    // near-miss spelling never reaches the copy button.
    const { type, subtype } = normalizePair(obj.type, obj.subtype);
    rows.push({
      eventDate: obj.eventDate || "",
      title: obj.title || "",
      type,
      subtype,
      comments: obj.comments || "",
      agreements: obj.agreements || "",
      sourceTitle: obj.sourceTitle || "",
      origin: obj.origin === "note" ? "note" : "generated",
      review: !!obj.review,
      reviewReason: obj.reviewReason || "",
      // Post-generation verification verdict (set by the verify pass).
      verify: obj.verify || "",
      verifyReason: obj.verifyReason || "",
    });
  }
  return rows;
}

export function rowsToNDJSON(rows) {
  return rows.map((r) => JSON.stringify(r)).join("\n");
}

// Newest activity first, matching how notes are listed everywhere else.
// Undated rows sink to the bottom rather than jumbling the top.
export function sortRows(rows) {
  return [...(rows || [])].sort((a, b) => {
    const ad = a.eventDate || "";
    const bd = b.eventDate || "";
    if (ad && bd && ad !== bd) return bd.localeCompare(ad);
    if (ad && !bd) return -1;
    if (!ad && bd) return 1;
    return (a.title || "").localeCompare(b.title || "");
  });
}

// Stable identity for a row across regenerations, so "filed in SFDC" sticks
// even after the report is rebuilt.
export function rowKey(row) {
  return `${row?.eventDate || ""}|${(row?.title || "").trim().toLowerCase()}`;
}

const esc = (s) => (s || "").replace(/\|/g, "\\|").replace(/\r?\n/g, " ").trim();

// Markdown table used for Save to Obsidian / Copy All.
export function rowsToMarkdown(rows) {
  const hasAgreements = (rows || []).some((r) => r.agreements);
  const head = hasAgreements
    ? "| Event Date | Title | Type | Subtype | EA/EP | Comments |"
    : "| Event Date | Title | Type | Subtype | Comments |";
  const rule = hasAgreements
    ? "|------------|-------|------|---------|-------|----------|"
    : "|------------|-------|------|---------|----------|";
  const lines = [
    head,
    rule,
    ...rows.map((r) => hasAgreements
      ? `| ${esc(r.eventDate)} | ${esc(r.title)} | ${esc(r.type)} | ${esc(r.subtype)} | ${esc(r.agreements)} | ${esc(r.comments)} |`
      : `| ${esc(r.eventDate)} | ${esc(r.title)} | ${esc(r.type)} | ${esc(r.subtype)} | ${esc(r.comments)} |`),
  ];
  return lines.join("\n");
}
